
const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
const defaultConfig = {
  siteTitle:'Dream Pets', badgeText:'Evento especial de pets', heroTitle:'Escolha seus pets favoritos',
  heroDesc:'Selecione até 3 pets, escolha a versão e envie sua solicitação. Site fã, feito para organização de um trabalho.',
  mainBtn:'Escolher pets', howTitle:'Como funciona?',
  howDesc:'Escolha no máximo 3 pets. Não envie senha, PIN ou dados privados de jogos. Use apenas informações autorizadas.',
  step1:'Veja os pets disponíveis.', step2:'Marque Normal, Neon, Mega, Fly ou Ride.', step3:'A resposta aparece no painel oculto.',
  noticeText:'Use somente um usuário público do jogo. Nunca coloque senha ou PIN.', userLabel:'Nome de usuário', phoneLabel:'Telefone do responsável',
  footerText:'© 2026 Dream Pets — site fã editável.',
  pets: [{"name": "Unicórnio", "rarity": "Legendary", "image": "assets/pets/unicornio.png", "enabled": true}, {"name": "Vaca", "rarity": "Rare", "image": "assets/pets/vaca.png", "enabled": true}, {"name": "Bat de Chocolate", "rarity": "Legendary", "image": "assets/pets/bat_chocolate.png", "enabled": true}, {"name": "Papagaio", "rarity": "Legendary", "image": "assets/pets/papagaio.png", "enabled": true}, {"name": "Bat de Morango", "rarity": "Legendary", "image": "assets/pets/bat_morango.png", "enabled": true}, {"name": "Canguru", "rarity": "Legendary", "image": "assets/pets/canguru.png", "enabled": true}, {"name": "Coruja", "rarity": "Legendary", "image": "assets/pets/coruja.png", "enabled": true}, {"name": "Elefante", "rarity": "Rare", "image": "assets/pets/elefante.png", "enabled": true}, {"name": "Girafa", "rarity": "Legendary", "image": "assets/pets/girafa.png", "enabled": true}, {"name": "Bat Dragon", "rarity": "Legendary", "image": "assets/pets/bat_dragon.png", "enabled": true}, {"name": "Frost Dragon", "rarity": "Legendary", "image": "assets/pets/frost_dragon.png", "enabled": true}, {"name": "Rena Ártica", "rarity": "Legendary", "image": "assets/pets/rena_artica.png", "enabled": true}, {"name": "Uni do Mal", "rarity": "Legendary", "image": "assets/pets/uni_mal.png", "enabled": true}, {"name": "Uni de Balão", "rarity": "Legendary", "image": "assets/pets/uni_balao.png", "enabled": true}, {"name": "Corujagato Rosa", "rarity": "Legendary", "image": "assets/pets/corujagato_rosa.png", "enabled": true}, {"name": "Pudim de Natal", "rarity": "Ultra-Rare", "image": "assets/pets/pudim_natal.png", "enabled": true}, {"name": "Dálmata", "rarity": "Ultra-Rare", "image": "assets/pets/dalmata.png", "enabled": true}, {"name": "Flamingo", "rarity": "Ultra-Rare", "image": "assets/pets/flamingo.png", "enabled": true}, {"name": "Porco Espinho", "rarity": "Ultra-Rare", "image": "assets/pets/porco_espinho.png", "enabled": true}]
};
let config = structuredClone(defaultConfig); let selected=[]; let modalMode='edit';
const $ = id => document.getElementById(id);
function show(id){$(id).classList.add('show')} function hide(id){$(id).classList.remove('show')}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>hide(b.dataset.close));
$('mainBtn').onclick=()=>document.querySelector('#pets').scrollIntoView({behavior:'smooth'});
async function loadConfig(){
  const {data,error} = await supabaseClient.from('site_config').select('*').eq('id',1).single();
  if(error || !data){ await supabaseClient.from('site_config').upsert({id:1,...defaultConfig}); config=structuredClone(defaultConfig); }
  else config={...defaultConfig,...data,pets:data.pets?.length?data.pets:defaultConfig.pets};
  applyConfig();
}
function applyConfig(){ ['siteTitle','badgeText','heroTitle','heroDesc','mainBtn','howTitle','howDesc','step1','step2','step3','noticeText','userLabel','phoneLabel','footerText'].forEach(k=>{ if($(k)) $(k).textContent=config[k]||''; }); renderHero(); renderPets(); renderCart(); buildEditFields(); renderAdminPets(); }
function renderHero(){ const box=$('heroPets'); box.innerHTML=''; (config.pets||[]).filter(p=>p.enabled!==false).slice(0,3).forEach(p=>{ const img=document.createElement('img'); img.className='heroPet'; img.src=p.image; img.alt=p.name; box.appendChild(img); }); }
function filteredPets(){ const q=$('searchPet').value.toLowerCase(); const r=$('filterRarity').value; return (config.pets||[]).filter(p=>p.enabled!==false).filter(p=>(!q||p.name.toLowerCase().includes(q))).filter(p=>(!r||p.rarity===r)); }
function renderPets(){ const grid=$('petsGrid'); grid.innerHTML=''; const list=filteredPets(); if(!list.length){grid.innerHTML='<div class="empty">Nenhum pet encontrado.</div>';return} list.forEach((p)=>{ const card=document.createElement('article'); card.className='petCard'; card.innerHTML=`<div class="petImgWrap"><img class="petImg" src="${p.image}" alt="${p.name}"></div><h3>${p.name}</h3><span class="rarity">${p.rarity||'Pet'}</span><div class="petOptions"><select class="version"><option>Normal</option><option>Neon</option><option>Mega Neon</option></select><select class="ability"><option>Normal</option><option>Fly</option><option>Ride</option><option>Fly Ride</option></select></div><button class="btn addBtn">Adicionar</button>`; card.querySelector('.addBtn').onclick=()=>addPet(p,card); grid.appendChild(card); }); }
$('searchPet').oninput=renderPets; $('filterRarity').onchange=renderPets;
function addPet(p,card){ if(selected.length>=3){alert('Você só pode escolher até 3 pets.');return} selected.push({name:p.name,rarity:p.rarity,image:p.image,version:card.querySelector('.version').value,ability:card.querySelector('.ability').value}); renderCart(); document.querySelector('#pedido').scrollIntoView({behavior:'smooth'}); }
function renderCart(){ const box=$('cartList'); if(!selected.length){box.innerHTML='<div class="empty">Nenhum pet escolhido ainda. Máximo: 3 pets.</div>';return} box.innerHTML=''; selected.forEach((p,i)=>{ const div=document.createElement('div'); div.className='cartItem'; div.innerHTML=`<span><img src="${p.image}"><b>${p.name}</b><br><small>${p.version} • ${p.ability}</small></span><button class="remove">Excluir</button>`; div.querySelector('button').onclick=()=>{selected.splice(i,1);renderCart()}; box.appendChild(div); }); }
$('sendBtn').onclick=async()=>{ const username=$('username').value.trim(), phone=$('phone').value.trim(); if(!username||!phone||!selected.length){$('msg').textContent='Preencha usuário, telefone e escolha pelo menos 1 pet.';return} const {error}=await supabaseClient.from('responses').insert({username,phone,pets:selected}); if(error) $('msg').textContent='Erro ao enviar: '+error.message; else {$('msg').textContent='Enviado com sucesso!'; $('username').value=''; $('phone').value=''; selected=[]; renderCart();} };
let ec=0, oc=0; $('editSecret').onclick=()=>{ if(++ec>=3){ec=0; askPass('edit')} setTimeout(()=>ec=0,900) }; $('ordersSecret').onclick=()=>{ if(++oc>=3){oc=0; askPass('orders')} setTimeout(()=>oc=0,900) };
function askPass(mode){modalMode=mode; $('passInput').value=''; $('passMsg').textContent=''; show('passModal'); setTimeout(()=>$('passInput').focus(),100)}
$('passBtn').onclick=()=>{ if($('passInput').value!==ADMIN_PASSWORD){$('passMsg').textContent='Senha incorreta.'; return} hide('passModal'); if(modalMode==='edit') show('editModal'); else {show('ordersModal'); loadOrders();} };
function buildEditFields(){ const fields=['siteTitle','badgeText','heroTitle','heroDesc','mainBtn','howTitle','howDesc','step1','step2','step3','noticeText','userLabel','phoneLabel','footerText']; const box=$('editFields'); box.innerHTML=''; fields.forEach(k=>{ const wrap=document.createElement('div'); wrap.innerHTML=`<label>${k}</label><textarea id="edit_${k}">${config[k]||''}</textarea>`; box.appendChild(wrap); }); }
$('saveTexts').onclick=async()=>{ ['siteTitle','badgeText','heroTitle','heroDesc','mainBtn','howTitle','howDesc','step1','step2','step3','noticeText','userLabel','phoneLabel','footerText'].forEach(k=>config[k]=$('edit_'+k).value); await saveConfig('Textos salvos para todos!'); };
function renderAdminPets(){ const box=$('petsAdminList'); box.innerHTML=''; (config.pets||[]).forEach((p,i)=>{ const div=document.createElement('div'); div.className='adminPet'; div.innerHTML=`<img src="${p.image}"><input value="${p.name||''}" data-i="${i}" data-k="name" placeholder="Nome"><select data-i="${i}" data-k="rarity"><option>Legendary</option><option>Ultra-Rare</option><option>Rare</option><option>Common</option></select><input value="${p.image||''}" data-i="${i}" data-k="image" placeholder="Caminho da imagem"><button class="remove">Excluir</button>`; div.querySelector('select').value=p.rarity||'Legendary'; div.querySelectorAll('input,select').forEach(inp=>inp.oninput=()=>{config.pets[inp.dataset.i][inp.dataset.k]=inp.value; if(inp.dataset.k==='image') div.querySelector('img').src=inp.value;}); div.querySelector('button').onclick=()=>{config.pets.splice(i,1); renderAdminPets();}; box.appendChild(div); }); }
$('addPetAdmin').onclick=()=>{config.pets.push({name:'Novo Pet',rarity:'Legendary',image:'assets/pets/unicornio.png',enabled:true}); renderAdminPets();};
$('savePetsAdmin').onclick=async()=>{ await saveConfig('Pets salvos para todos!'); };
async function saveConfig(msg){ const payload={id:1,...config,updated_at:new Date().toISOString()}; const {error}=await supabaseClient.from('site_config').upsert(payload); if(error) $('saveMsg').textContent='Erro: '+error.message; else {$('saveMsg').textContent=msg; applyConfig();} }
document.querySelectorAll('.tab').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); document.querySelectorAll('.tabPage').forEach(p=>p.classList.remove('show')); $('tab-'+btn.dataset.tab).classList.add('show');});
async function loadOrders(){ const box=$('ordersList'); box.innerHTML='<p>Carregando...</p>'; const {data,error}=await supabaseClient.from('responses').select('*').order('created_at',{ascending:false}); if(error){box.innerHTML='<div class="empty">Erro ao carregar: '+error.message+'</div>'; return} const q=$('searchOrders').value.toLowerCase(); const rows=(data||[]).filter(r=>!q||(r.username||'').toLowerCase().includes(q)||(r.phone||'').toLowerCase().includes(q)); if(!rows.length){box.innerHTML='<div class="empty">Nenhuma resposta encontrada.</div>';return} box.innerHTML=''; rows.forEach(r=>{ const pets=(r.pets||[]).map(p=>`<div><img src="${p.image}"><b>${p.name}</b> — ${p.version} • ${p.ability}</div>`).join(''); const div=document.createElement('div'); div.className='response'; div.innerHTML=`<b>Usuário:</b> ${r.username}<br><b>Telefone:</b> ${r.phone}<br><b>Pets:</b>${pets}<button class="remove">Excluir</button>`; div.querySelector('button').onclick=async()=>{await supabaseClient.from('responses').delete().eq('id',r.id); loadOrders();}; box.appendChild(div); }); }
$('refreshOrders').onclick=loadOrders; $('searchOrders').oninput=loadOrders;
loadConfig();
